apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "appname" . }}
    track: "{{ .Values.application.track }}"
    tier: "{{ .Values.application.tier }}"
    release: {{ .Release.Name }}
    service: mysql
  name: mysql
spec:
  ports:
  - name: mysql-port
    port: 3306
    targetPort: 3306
  selector:
    app: {{ template "appname" . }}
    track: "{{ .Values.application.track }}"
    tier: "{{ .Values.application.tier }}"
    release: {{ .Release.Name }}
    service: mysql
status:
  loadBalancer: {}
